"""add Users, Transaction

Revision ID: 939f11f678fe
Revises: 
Create Date: 2023-03-25 23:08:15.813441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models import db

# revision identifiers, used by Alembic.
revision = '939f11f678fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    db.create_all(bind=op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    db.drop_all(bind=op.get_bind())
    # ### end Alembic commands ###
